name: CI/CD Pipeline for Java Application

on:
  push:
    branches:
      - main  # Kích hoạt CI/CD khi có thay đổi trên nhánh 'main'
  pull_request:
    branches:
      - main  # Kích hoạt CI/CD khi có pull request vào nhánh 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Bước 2: Cài đặt JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          java-package: jdk
          architecture: x64
          distribution: 'temurin'  # Thêm tham số này để chỉ rõ loại JDK
          check-latest: false

      # Bước 3: Build ứng dụng với Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Bước 4: Set up SSH key from GitHub Secrets
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Thêm vào known_hosts để tránh cảnh báo khi kết nối lần đầu
          ssh-keyscan -H 52.207.237.32 >> ~/.ssh/known_hosts

      # Bước 5: Deploy lên AWS EC2
      - name: Deploy to AWS EC2
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no target/dtdm_demo.war ubuntu@52.207.237.32:/var/lib/tomcat10/webapps/
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@52.207.237.32 'sudo systemctl restart tomcat10'
